config/routes.rb
Rails.application.routes.draw do
  root 'daily_reports#compare'
  get 'daily_reports/compare'
  resources :daily_reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
end

app/models/population.rb
class Population < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: [:edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json
  def index
    @daily_reports = DailyReport.all
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
    @country1 = params[:c1]
    @reports = DailyReport.select("day, sum(deaths) as deaths, sum(confirmed) as confirmed, sum(recovery) as recovery").where(:country => @country1).group(:country).group(:day).order(day: :desc)
  end

  # GET /daily_reports/new
  def new
    @daily_report = DailyReport.new
  end

  # GET /daily_reports/1/edit
  def edit
  end

  # GET /daily_reports/compare?c1=Brazil&c2=Italy
  def compare

    @avaialble_countries = DailyReport.select(:country).distinct(:country).order(:country)

    @reference = 1000000
    @country1 = params[:c1].presence || "Brazil"
    @country2 = params[:c2] || "Italy"
    @country1_first_confirmed = DailyReport.where(:country => @country1).where('confirmed > 0').order(:day).first
    @country2_first_confirmed = DailyReport.where(:country => @country2).where('confirmed > 0').order(:day).first
    @country1_first_death = DailyReport.where(:country => @country1).where('deaths > 0').order(:day).first
    @country2_first_death = DailyReport.where(:country => @country2).where('deaths > 0').order(:day).first
    @country1_7_days_death = DailyReport
                                 .select("day, sum(deaths) as deaths, sum(confirmed) as confirmed")
                                 .where(:country => @country1).where(:day => @country1_first_confirmed.day + 7)
                                 .group(:country).group(:day).order(:day).first
    @country2_7_days_death = DailyReport
                                 .select("day, sum(deaths) as deaths, sum(confirmed) as confirmed")
                                 .where(:country => @country2).where(:day => @country2_first_confirmed.day + 7)
                                 .group(:country).group(:day).order(:day).first
    # @country1_14_days_death = DailyReport.where(:country => @country1).where(:day => @country1_first_confirmed.day + 14).group(:country).group(:day).first
    # @country2_14_days_death = DailyReport.where(:country => @country2).where(:day => @country2_first_confirmed.day + 14).group(:country).group(:day).first
    # @country1_21_days_death = DailyReport.where(:country => @country1).where(:day => @country1_first_confirmed.day + 21).group(:country).group(:day).first
    # @country2_21_days_death = DailyReport.where(:country => @country2).where(:day => @country2_first_confirmed.day + 21).group(:country).group(:day).first
    # @country1_30_days_death = DailyReport.where(:country => @country1).where(:day => @country1_first_confirmed.day + 30).group(:country).group(:day).first
    # @country2_30_days_death = DailyReport.where(:country => @country2).where(:day => @country2_first_confirmed.day + 30).group(:country).group(:day).first
    # @country1_last = DailyReport.where(:country => @country1).group(:country).group(:day).order(:day).last
    # @country2_last = DailyReport.where(:country => @country2).group(:country).group(:day).order(:day).last
    @country1_14_days_death = DailyReport.new
    @country2_14_days_death = DailyReport.new
    @country1_21_days_death = DailyReport.new
    @country2_21_days_death = DailyReport.new
    @country1_30_days_death = DailyReport.new
    @country2_30_days_death = DailyReport.new
    @country1_last = DailyReport.new
    @country2_last = DailyReport.new
    @country1_population = Population.where(:country => @country1).first
    @country2_population = Population.where(:country => @country2).first

  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_reports/1
  # PATCH/PUT /daily_reports/1.json
  def update
    respond_to do |format|
      if @daily_report.update(daily_report_params)
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_report }
      else
        format.html { render :edit }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_reports/1
  # DELETE /daily_reports/1.json
  def destroy
    @daily_report.destroy
    respond_to do |format|
      format.html { redirect_to daily_reports_url, notice: 'Daily report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_daily_report
    @daily_report = DailyReport.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def daily_report_params
    params.require(:daily_report).permit(:country, :day, :confirmed, :deaths, :recovery)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper

  # return @reference * @country1_last&.deaths / @country1_population&.total
  def per_indice(ref, hab, indice)
    if ref == nil || ref == 0 || hab == nil || hab == 0
      return " - "
    end
    return indice * ref / hab
  end
end

app/views/daily_reports/_form.html.erb
<%= form_with(model: daily_report, local: true) do |form| %>
  <% if daily_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_report.errors.count, "error") %> prohibited this daily_report from being saved:</h2>

      <ul>
        <% daily_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="field">
    <%= form.label :confirmed %>
    <%= form.number_field :confirmed %>
  </div>

  <div class="field">
    <%= form.label :deaths %>
    <%= form.number_field :deaths %>
  </div>

  <div class="field">
    <%= form.label :recovery %>
    <%= form.number_field :recovery %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_reports/compare.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-row">
    <div class="col">
      <select id="select1" class="form-control" name="c1">
        <% @avaialble_countries.each do |c| %>
          <option value="<%= c.country %>"><%= c.country %></option>
        <% end %>
      </select>
    </div>
    <div class="col">
      <select id="select2" class="form-control select2" name="c2">
        <% @avaialble_countries.each do |c| %>
          <option value="<%= c.country %>"><%= c.country %></option>
        <% end %>
      </select>
    </div>
    <div class="col">
      <input class="btn btn-secondary" type="submit" value="Compare">
    </div>
  </div>
</form>
<br>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">País</th>
    <th scope="col" colspan="2"><%= @country1 %></th>
    <th scope="col" colspan="2"><%= @country2 %></th>
  </tr>
  </thead>
  <tr>
    <td>População</td>
    <td colspan="2"><%= number_to_human(@country1_population&.total, significant: false) %></td>
    <td colspan="2"><%= number_to_human(@country2_population&.total, significant: false) %></td>
  </tr>
  <tr>
    <td>Primeiro contaminado</td>
    <td colspan="2"><%= I18n.l(@country1_first_confirmed&.day) %>
      <a target="_blank" href="<%= "/daily_reports/1?c1=#{@country1}" %>" class="btn btn-sm btn-outline-secondary">Ver diários</a></td>
    <td colspan="2"><%= I18n.l(@country2_first_confirmed&.day) %>
      <a target="_blank" href="<%= "/daily_reports/1?c1=#{@country2}" %>" class="btn btn-sm btn-outline-secondary">Ver diários</a></td>
  </tr>
  <tr>
    <td>Primeira morte</td>
    <td colspan="2"><%= @country1_first_death&.day && I18n.l(@country1_first_death&.day) %></td>
    <td colspan="2"><%= @country2_first_death&.day && I18n.l(@country2_first_death&.day) %></td>
  </tr>
  <tr>
    <td rowspan="2">7 dias</td>
    <td>Confirmados: <%= @country1_7_days_death&.confirmed %></td>
    <td>Por milhão:  <%= per_indice(@country1_7_days_death&.confirmed, @country1_population&.total, @reference) %></td>
    <td>Confirmados: <%= @country2_7_days_death&.confirmed %></td>
    <td>Por milhão:  <%= per_indice(@country2_7_days_death&.confirmed, @country2_population&.total, @reference) %></td>
  </tr>
<!--  <tr>-->
<!--    <td>Mortos: <%#= @country1_7_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_7_days_death&.deaths, @country1_population&.total, @reference) %></td>-->
<!--    <td>Mortos: <%#= @country2_7_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_7_days_death&.deaths, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td rowspan="2">14 dias</td>-->
<!--    <td>Confirmados: <%#= @country1_14_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_14_days_death&.confirmed, @country1_population&.total, @reference) %></td>-->
<!--    <td>Confirmados: <%#= @country2_14_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_14_days_death&.confirmed, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td>Mortos: <%#= @country1_14_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_14_days_death&.deaths, @country1_population&.total, @reference) %></td>-->
<!--    <td>Mortos: <%#= @country2_14_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_14_days_death&.deaths, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td rowspan="2">21 dias</td>-->
<!--    <td>Confirmados: <%#= @country1_21_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_21_days_death&.confirmed, @country1_population&.total, @reference) %></td>-->
<!--    <td>Confirmados: <%#= @country2_21_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_21_days_death&.confirmed, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td>Mortos: <%#= @country1_21_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_21_days_death&.deaths, @country1_population&.total, @reference) %></td>-->
<!--    <td>Mortos: <%#= @country2_21_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_21_days_death&.deaths, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td rowspan="2">30 dias</td>-->
<!--    <td>Confirmados: <%#= @country1_30_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_30_days_death&.confirmed, @country1_population&.total, @reference) %></td>-->
<!--    <td>Confirmados: <%#= @country2_30_days_death&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_30_days_death&.confirmed, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td>Mortos: <%#= @country1_30_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_30_days_death&.deaths, @country1_population&.total, @reference) %></td>-->
<!--    <td>Mortos: <%#= @country2_30_days_death&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_30_days_death&.deaths, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td rowspan="2">Último registro</td>-->
<!--    <td>(<%#= I18n.l(@country1_last&.day) %>) Confirmados total: <%#= @country1_last&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_last&.confirmed, @country1_population&.total, @reference) %></td>-->
<!--    <td>(<%#= I18n.l(@country2_last&.day) %>) Total confirmados: <%#= @country2_last&.confirmed %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_last&.confirmed, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td>Total mortes: <%#= @country1_last&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country1_last&.deaths, @country1_population&.total, @reference) %></td>-->
<!--    <td>Total mortes: <%#= @country2_last&.deaths %></td>-->
<!--    <td>Por milhão:  <%#= per_indice(@country2_last&.deaths, @country2_population&.total, @reference) %></td>-->
<!--  </tr>-->
  <tfoot>
  <tr>
    <td colspan="5">Fonte:
      <a href="https://databank.worldbank.org/reports.aspx?source=2&series=SP.POP.TOTL,SP.POP.0014.TO.ZS,SP.POP.1564.TO.ZS,SP.POP.65UP.TO.ZS,SP.POP.DPND.YG,SP.POP.DPND.OL,SP.DYN.CDRT.IN,SP.DYN.CBRT.IN#">
        Population</a> and <a href="https://github.com/CSSEGISandData/COVID-19">Daily Reports</a></td>
  </tr>
  </tfoot>
</table>

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
  />
<!-- Include Choices JavaScript (latest) -->
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>

<script>
    new Choices('#select1');
    new Choices('#select2');
</script>

app/views/daily_reports/edit.html.erb
<h1>Editing Daily Report</h1>

<%= render 'form', daily_report: @daily_report %>

<%= link_to 'Show', @daily_report %> |
<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Reports</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Day</th>
      <th>Confirmed</th>
      <th>Deaths</th>
      <th>Recovery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_reports.each do |daily_report| %>
      <tr>
        <td><%= daily_report.country %></td>
        <td><%= daily_report.day %></td>
        <td><%= daily_report.confirmed %></td>
        <td><%= daily_report.deaths %></td>
        <td><%= daily_report.recovery %></td>
        <td><%= link_to 'Show', daily_report %></td>
        <td><%= link_to 'Edit', edit_daily_report_path(daily_report) %></td>
        <td><%= link_to 'Destroy', daily_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Report', new_daily_report_path %>

app/views/daily_reports/new.html.erb
<h1>New Daily Report</h1>

<%= render 'form', daily_report: @daily_report %>

<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/show.html.slim
h1 Histórico de #{@country1}

table.table
  thead.thead-dark
    tr
      th[scope="col"] Dia
      th[scope="col"] Confirmados
      th[scope="col"] Mortes
      th[scope="col"] Recuperados
  - @reports.each_with_index do |rep, index|
    tr
      td = I18n.l(rep.day)
      td #{rep.confirmed} [ +#{@reports[index+1]&.confirmed && (@reports[index]&.confirmed - @reports[index+1].confirmed) } ]
      td #{rep.deaths} [ +#{@reports[index+1]&.deaths && (@reports[index].deaths - @reports[index+1].deaths) } ]
      td #{rep.recovery} [ +#{@reports[index+1]&.recovery && (@reports[index].recovery - @reports[index+1].recovery) } ]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidComparator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>